/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Cart: () => import('#controllers/cart_controller'),
  Discounts: () => import('#controllers/discounts_controller'),
  Inventory: () => import('#controllers/inventory_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Orders: () => import('#controllers/orders_controller'),
  Products: () => import('#controllers/products_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Stores: () => import('#controllers/stores_controller'),
}
