/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CartItemSchema extends BaseModel {
  static $columns = ['cartId', 'createdAt', 'id', 'productId', 'quantity', 'updatedAt'] as const
  $columns = CartItemSchema.$columns
  @column()
  declare cartId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare productId: number
  @column()
  declare quantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CartSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'updatedAt', 'userId'] as const
  $columns = CartSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class OrderItemSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'orderId', 'productId', 'quantity', 'returnedQuantity', 'storeId', 'totalPrice', 'unitPrice', 'updatedAt'] as const
  $columns = OrderItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderId: number
  @column()
  declare productId: number
  @column()
  declare quantity: number
  @column()
  declare returnedQuantity: number
  @column()
  declare storeId: number
  @column()
  declare totalPrice: string
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderSchema extends BaseModel {
  static $columns = ['createdAt', 'customerLatitude', 'customerLongitude', 'deliveryAddress', 'discountType', 'id', 'platformDiscountAmount', 'productDiscountAmount', 'status', 'subtotal', 'total', 'updatedAt', 'userId'] as const
  $columns = OrderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerLatitude: string | null
  @column()
  declare customerLongitude: string | null
  @column()
  declare deliveryAddress: string
  @column()
  declare discountType: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare platformDiscountAmount: string
  @column()
  declare productDiscountAmount: string
  @column()
  declare status: string
  @column()
  declare subtotal: string
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PlatformDiscountSchema extends BaseModel {
  static $columns = ['createdAt', 'discountPercentage', 'id', 'isActive', 'minOrderAmount', 'name', 'updatedAt'] as const
  $columns = PlatformDiscountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare discountPercentage: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare minOrderAmount: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductDiscountSchema extends BaseModel {
  static $columns = ['createdAt', 'discountPercentage', 'id', 'isActive', 'minQuantity', 'productId', 'updatedAt'] as const
  $columns = ProductDiscountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare discountPercentage: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare minQuantity: number
  @column()
  declare productId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'imageUrl', 'isActive', 'name', 'price', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare price: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StoreInventorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'productId', 'quantity', 'storeId', 'updatedAt'] as const
  $columns = StoreInventorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare productId: number
  @column()
  declare quantity: number
  @column()
  declare storeId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StoreSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'id', 'isActive', 'latitude', 'longitude', 'name', 'updatedAt'] as const
  $columns = StoreSchema.$columns
  @column()
  declare address: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare latitude: string | null
  @column()
  declare longitude: string | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
